### ISSUE TITLE
Testium looking for an app to be running on port 8000

### ISSUE THREAD

**Issue by silvercross313** [groupon-testium/testium#150]
I am using Testium as a framework for some sanity tests I'm writing.  These sanity tests will run against my app in prod periodically to basically ensure that key elements are always visible.

However, because I'm running this independently of the web app project itself, Testium always gives me an error on startup saying that there is no app listening on port 8000.  I've tried setting launch = false in the .testiumrc file, but Testium still seems to be trying to launch the app anyway.  I can get around this during development by starting an app on port 8000, but in my CI job there isn't a way around it.  Do you know how I might disable any app checking in Testium?

**Comment by silvercross313** [comment]
Any progress on this?  Is there any additional info I can provide to help with debugging?  Thanks!

**Comment by EndangeredMassa** [comment]
If it's a different port that is already started, you should be able to set the app port in the config and set launch to false. If the app is on a different host, I don't think there's a way to do that, currently.

I'm working making the app section optional entirely. It turns out that the interactive console is another user case where you don't want to require app startup logic.

**Comment by EndangeredMassa** [comment]
PR: https://github.com/groupon-testium/testium/pull/154
